[package]
name = "od-badge-signup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = { version = "0.11", features = ["json"] }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }

[dev-dependencies]
httptest = "0.15.4"
claim = "0.5"
