[package]
name = "deathnote-signup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "service"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = { version = "0.11", features = ["json"] }
opentelemetry = { version = "*", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
serde_with = "1.14.0"

[dev-dependencies]
mockall = "0.11.1"
httpmock = "0.6"
claim = "0.5"
