version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '16686:16686'
      - '14250:14250'
      - '14268:14268'